name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Downgrade mingw to 11.2.0
        if: runner.os == 'Windows'
        run: choco install mingw --version 11.2.0 --allow-downgrade
      - name: Setup GStreamer
        id: setup_gstreamer
        uses: RSWilli/setup-gstreamer@5472e33168ba7b1f3bb01dc81ca067e263633824
        with:
          version: 1.22.0
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.21.0"
      - name: build
        shell: bash
        run: |
          packages=$(go list ./...)
          for package in $packages; do
            echo "Building: $package"
            go build $package || exit 1
            echo "Build done: $package"
          done
