name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Tests on codebase
    runs-on: ubuntu-latest
    steps:
      - name: Setup GStreamer
        id: setup_gstreamer
        uses: RSWilli/setup-gstreamer@5472e33168ba7b1f3bb01dc81ca067e263633824
        with:
          version: 1.22.6
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.21.0"
      - name: Check formatting
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"
      - name: Check spellings
        uses: reviewdog/action-misspell@v1
        with:
          locale: "US"
          fail_on_error: true
          filter_mode: nofilter
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
          min-go-version: "1.21"
